name: Deploy to Google App Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: pip install -r requirements.txt

    # - name: Run tests
    #   run: python manage.py test

    - name: Deploy to Google App Engine
      uses: google-github-actions/deploy-appengine@main
      with:
        credentials: ${{ secrets.GCP_SA_KEY }}
        project_id: nomadic-vehicle-404406
        version: v1
        deliverables: app.yml
